-- SQL Setup for Katapatan SafeWatch

-- 1. Profiles Table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE,
  full_name TEXT,
  address TEXT,
  verification_status TEXT DEFAULT 'verified',
  phone_number TEXT,
  PRIMARY KEY (id)
);

-- 2. Reports Table
CREATE TABLE reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT,
  type TEXT NOT NULL,
  location TEXT,
  lat FLOAT8 NOT NULL,
  lng FLOAT8 NOT NULL,
  user_id UUID REFERENCES auth.users(id),
  color TEXT
);

-- 3. SOS Alerts Table
CREATE TABLE sos_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID REFERENCES auth.users(id),
  lat FLOAT8,
  lng FLOAT8,
  status TEXT DEFAULT 'active'
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE sos_alerts ENABLE ROW LEVEL SECURITY;

-- Simple Policies (Allow authenticated read/write for now)
-- NOTE: In production, these should be more restrictive
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Reports are viewable by everyone." ON reports FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert reports." ON reports FOR INSERT WITH CHECK (true);

CREATE POLICY "SOS Alerts are viewable by everyone." ON sos_alerts FOR SELECT USING (true);
CREATE POLICY "Authenticated users can trigger SOS." ON sos_alerts FOR INSERT WITH CHECK (true);
